version: "3.1"
services:
  db:
    image: "mysql:8.0"
    ports:
      - 3301:3306
    environment:
      MYSQL_ROOT_PASSWORD: "1"
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: rest-api
    expose:
      - 3306
